---
title: "Worked Example - Bird Migration"
author: "Katy Brown"
format: html
---
```{r}
library(tidyverse)
library(gt)
```

Read the bird breeding site data frame and look at it with `gt()`.

```{r}
bird_breeding_sites <- read_csv("data/breeding_site_locations.csv")

gt(bird_breeding_sites)
```

Preview the data with `glimpse()`.

```{r}
glimpse(bird_breeding_sites)
```

Read the bird migration site data.
```{r}
bird_migration_sites <- read_csv("data/migratory_connectivity_dataset.csv")
gt(head(bird_migration_sites))
```
Summarise the data frame

```{r}
glimpse(bird_migration_sites)
```

Filter columns in bird_breeding_sites data frame

```{r}
bird_breeding_selected <- bird_breeding_sites |>
  select(Site, Longitude, Latitude) |>
  distinct() |>
  rename(Breeding_Longitude = Longitude, Breeding_Latitude = Latitude)

gt(bird_breeding_selected)
```

Filter columns in bird_migration_sites data frame

```{r}
bird_migration_selected <- bird_migration_sites |>
  select(Site,
         winterLongitude,
         winterLatitude,
         pslon,
         pslat,
         iblon,
         iblat,
         awestlon,
         awestlat) |>
  unique() |>
  rename(
    Winter_Longitude = winterLongitude,
    Winter_Latitude = winterLatitude,
    Stopover_Longitude = pslon,
    Stopover_Latitude = pslat,
    Iberian_Longitude = iblon,
    Iberian_Latitude = iblat,
    Westmost_Longitude = awestlon,
    Westmost_Latitude = awestlat
  )

gt(head(bird_migration_selected))
```



```{r}
bird_breeding_exc <- bird_breeding_selected |>
  filter(Site != "Spain")

bird_migration_exc <- bird_migration_selected |>
  filter(Site != "Spain")

gt(bird_breeding_exc)
```
Calculate median longitude and latitude in the bird_migration data frame.

```{r}
bird_migration_grouped <- bird_migration_exc |> group_by(Site)

bird_migration_summary <- bird_migration_grouped |>
  summarise(
    Stopover_Longitude = median(Stopover_Longitude, na.rm = TRUE),
    Stopover_Latitude = median(Stopover_Latitude, na.rm = TRUE),
    Winter_Longitude = median(Winter_Longitude, na.rm = TRUE),
    Winter_Latitude = median(Winter_Latitude, na.rm = TRUE),
    Iberian_Longitude = median(Iberian_Longitude, na.rm = TRUE),
    Iberian_Latitude = median(Iberian_Latitude, na.rm = TRUE),
    Westmost_Longitude = median(Westmost_Longitude, na.rm = TRUE),
    Westmost_Latitude = median(Westmost_Latitude, na.rm = TRUE)
  )
gt(bird_migration_summary)
```

Join the two data frames

```{r}
combined_bird_data <- full_join(bird_breeding_exc, bird_migration_summary)

gt(combined_bird_data)
```
```{r}
combined_bird_piv <- combined_bird_data |>
  pivot_longer(
    cols = ends_with(c("_Longitude", "_Latitude")),
    names_sep = "_",
    names_to = c("Location_Type", ".value")
  )

gt(combined_bird_piv)
```

Save file

```{r}
write_csv(combined_bird_piv, "output/combined_birds.csv")
```